-- AlterTable
ALTER TABLE `reservation` ADD COLUMN `tableType` ENUM('NORMAL', 'VIP') NOT NULL DEFAULT 'NORMAL';

-- CreateTable
CREATE TABLE `Notification` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `message` VARCHAR(191) NOT NULL,
    `type` ENUM('RESERVATION', 'REVIEW', 'PROMOTION', 'SYSTEM') NOT NULL DEFAULT 'SYSTEM',
    `link` VARCHAR(191) NULL,
    `isRead` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
